<div id="zendesk-form" data-bind="scope: 'zendeskForm'">
    <!-- ko template: getTemplate() --><!--/ko-->
</div>
<script type="text/x-magento-init">
    {
        "*": {
            "Magento_Ui/js/core/app": {
                "components": {
                    "zendeskForm": {
                        "component": "Dynamic_Contact/js/form",
                        "formUrl": "<?= /* @escapeNotVerified */ $block->getPostActionUrl() ?>",
                        "formLoginUrl": "<?= /* @escapeNotVerified */ $block->getAjaxLoginActionUrl() ?>"
                    }
                }
            }
        }
    }
</script>

